services:
  bot:
    build:
      context: .
      target: dev
    env_file:
      - .env
    environment:
      - blah=blah
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
        restart: true
  
  database:
    image: postgres
    container_name: database
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d expense_db" ]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=expense_db
    ports:
      - 5432:5432

volumes:
  db-data: